salle:
    pattern:  /
    defaults: { _controller: "EcoleDeMusiqueWelcomeBundle:Salle:index" }

salle_show:
    pattern:  /{id}/show
    defaults: { _controller: "EcoleDeMusiqueWelcomeBundle:Salle:show" }

salle_new:
    pattern:  /new
    defaults: { _controller: "EcoleDeMusiqueWelcomeBundle:Salle:new" }

salle_create:
    pattern:  /create
    defaults: { _controller: "EcoleDeMusiqueWelcomeBundle:Salle:create" }
    requirements: { _method: post }

salle_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EcoleDeMusiqueWelcomeBundle:Salle:edit" }

salle_update:
    pattern:  /{id}/update
    defaults: { _controller: "EcoleDeMusiqueWelcomeBundle:Salle:update" }
    requirements: { _method: post }

salle_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EcoleDeMusiqueWelcomeBundle:Salle:delete" }
    requirements: { _method: get }
