<?php

namespace Proxies\__CG__\EcoleDeMusique\WelcomeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Regie extends \EcoleDeMusique\WelcomeBundle\Entity\Regie implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCapv($capv)
    {
        $this->__load();
        return parent::setCapv($capv);
    }

    public function getCapv()
    {
        $this->__load();
        return parent::getCapv();
    }

    public function setEnfantAdulte($enfantAdulte)
    {
        $this->__load();
        return parent::setEnfantAdulte($enfantAdulte);
    }

    public function getEnfantAdulte()
    {
        $this->__load();
        return parent::getEnfantAdulte();
    }

    public function setCycleParcours($cycleParcours)
    {
        $this->__load();
        return parent::setCycleParcours($cycleParcours);
    }

    public function getCycleParcours()
    {
        $this->__load();
        return parent::getCycleParcours();
    }

    public function setIntru2($intru2)
    {
        $this->__load();
        return parent::setIntru2($intru2);
    }

    public function getIntru2()
    {
        $this->__load();
        return parent::getIntru2();
    }

    public function setIntru3($intru3)
    {
        $this->__load();
        return parent::setIntru3($intru3);
    }

    public function getIntru3()
    {
        $this->__load();
        return parent::getIntru3();
    }

    public function setSommeSansRemise($sommeSansRemise)
    {
        $this->__load();
        return parent::setSommeSansRemise($sommeSansRemise);
    }

    public function getSommeSansRemise()
    {
        $this->__load();
        return parent::getSommeSansRemise();
    }

    public function setRemise($remise)
    {
        $this->__load();
        return parent::setRemise($remise);
    }

    public function getRemise()
    {
        $this->__load();
        return parent::getRemise();
    }

    public function setSommeAvecRemise($sommeAvecRemise)
    {
        $this->__load();
        return parent::setSommeAvecRemise($sommeAvecRemise);
    }

    public function getSommeAvecRemise()
    {
        $this->__load();
        return parent::getSommeAvecRemise();
    }

    public function setRegies(\EcoleDeMusique\WelcomeBundle\Entity\Eleve $regies = NULL)
    {
        $this->__load();
        return parent::setRegies($regies);
    }

    public function getRegies()
    {
        $this->__load();
        return parent::getRegies();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setAnneDeCours($anneDeCours)
    {
        $this->__load();
        return parent::setAnneDeCours($anneDeCours);
    }

    public function getAnneDeCours()
    {
        $this->__load();
        return parent::getAnneDeCours();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'capv', 'enfantAdulte', 'cycleParcours', 'intru2', 'intru3', 'sommeSansRemise', 'remise', 'sommeAvecRemise', 'anneDeCours', 'regies');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}