parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     ecoleDeMusique
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       mail.ville-voreppe.fr
    
    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt