<?php

namespace EcoleDeMusique\WelcomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoordonneePrincipaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordonneePrincipaleRepository extends EntityRepository
{
}
