<?php

namespace EcoleDeMusique\WelcomeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleCommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegieRepository extends EntityRepository {

    

}
