parameters:
#    ecole_de_musique_welcome.example.class: EcoleDeMusique\WelcomeBundle\Example

services:
#    ecole_de_musique_welcome.example:
#        class: %ecole_de_musique_welcome.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
