parameters:
#    ecole_de_musique_welcome.example.class: EcoleDeMusique\WelcomeBundle\Example

services:
#    ecole_de_musique_welcome.example:
#        class: %ecole_de_musique_welcome.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    #form.type.periodefonction:
     #   class: ecoleDeMusique\WelComeBundle\Form\FamilleType
     #   arguments: ["@doctrine.orm.entity_manager"]
     #   tags:
     #      - { name: form.type, alias: ecoledemusique_welcomebundle_familletype }