<?php

namespace Proxies\__CG__\EcoleDeMusique\WelcomeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Regie extends \EcoleDeMusique\WelcomeBundle\Entity\Regie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'id', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'capv', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'enfantAdulte', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'cycleParcours', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'intru2', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'intru3', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'sommeSansRemise', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'remise', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'sommeAvecRemise', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'regies', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'anneDeCours');
        }

        return array('__isInitialized__', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'id', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'capv', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'enfantAdulte', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'cycleParcours', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'intru2', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'intru3', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'sommeSansRemise', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'remise', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'sommeAvecRemise', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'regies', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Regie' . "\0" . 'anneDeCours');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Regie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapv($capv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapv', array($capv));

        return parent::setCapv($capv);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapv', array());

        return parent::getCapv();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnfantAdulte($enfantAdulte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnfantAdulte', array($enfantAdulte));

        return parent::setEnfantAdulte($enfantAdulte);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnfantAdulte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnfantAdulte', array());

        return parent::getEnfantAdulte();
    }

    /**
     * {@inheritDoc}
     */
    public function setCycleParcours($cycleParcours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCycleParcours', array($cycleParcours));

        return parent::setCycleParcours($cycleParcours);
    }

    /**
     * {@inheritDoc}
     */
    public function getCycleParcours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCycleParcours', array());

        return parent::getCycleParcours();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntru2($intru2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntru2', array($intru2));

        return parent::setIntru2($intru2);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntru2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntru2', array());

        return parent::getIntru2();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntru3($intru3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntru3', array($intru3));

        return parent::setIntru3($intru3);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntru3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntru3', array());

        return parent::getIntru3();
    }

    /**
     * {@inheritDoc}
     */
    public function setSommeSansRemise($sommeSansRemise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSommeSansRemise', array($sommeSansRemise));

        return parent::setSommeSansRemise($sommeSansRemise);
    }

    /**
     * {@inheritDoc}
     */
    public function getSommeSansRemise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSommeSansRemise', array());

        return parent::getSommeSansRemise();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemise($remise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemise', array($remise));

        return parent::setRemise($remise);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemise', array());

        return parent::getRemise();
    }

    /**
     * {@inheritDoc}
     */
    public function setSommeAvecRemise($sommeAvecRemise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSommeAvecRemise', array($sommeAvecRemise));

        return parent::setSommeAvecRemise($sommeAvecRemise);
    }

    /**
     * {@inheritDoc}
     */
    public function getSommeAvecRemise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSommeAvecRemise', array());

        return parent::getSommeAvecRemise();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegies(\EcoleDeMusique\WelcomeBundle\Entity\Eleve $regies = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegies', array($regies));

        return parent::setRegies($regies);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegies()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegies', array());

        return parent::getRegies();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneDeCours($anneDeCours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneDeCours', array($anneDeCours));

        return parent::setAnneDeCours($anneDeCours);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneDeCours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneDeCours', array());

        return parent::getAnneDeCours();
    }

}
