<?php

namespace Proxies\__CG__\EcoleDeMusique\WelcomeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Paiement extends \EcoleDeMusique\WelcomeBundle\Entity\Paiement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'id', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'interupt', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'dateInterupt', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'sommePeriode', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'paiementPeriode', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'eleve', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'sommeTotal');
        }

        return array('__isInitialized__', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'id', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'interupt', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'dateInterupt', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'sommePeriode', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'paiementPeriode', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'eleve', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Paiement' . "\0" . 'sommeTotal');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Paiement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterupt($interupt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterupt', array($interupt));

        return parent::setInterupt($interupt);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterupt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterupt', array());

        return parent::getInterupt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateInterupt($dateInterupt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateInterupt', array($dateInterupt));

        return parent::setDateInterupt($dateInterupt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateInterupt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateInterupt', array());

        return parent::getDateInterupt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSommePeriode($sommePeriode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSommePeriode', array($sommePeriode));

        return parent::setSommePeriode($sommePeriode);
    }

    /**
     * {@inheritDoc}
     */
    public function getSommePeriode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSommePeriode', array());

        return parent::getSommePeriode();
    }

    /**
     * {@inheritDoc}
     */
    public function setSommeTotal($sommeTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSommeTotal', array($sommeTotal));

        return parent::setSommeTotal($sommeTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSommeTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSommeTotal', array());

        return parent::getSommeTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setEleve(\EcoleDeMusique\WelcomeBundle\Entity\Eleve $eleve = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEleve', array($eleve));

        return parent::setEleve($eleve);
    }

    /**
     * {@inheritDoc}
     */
    public function getEleve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEleve', array());

        return parent::getEleve();
    }

}
