<?php

namespace Proxies\__CG__\EcoleDeMusique\WelcomeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Paiement extends \EcoleDeMusique\WelcomeBundle\Entity\Paiement implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setInterupt($interupt)
    {
        $this->__load();
        return parent::setInterupt($interupt);
    }

    public function getInterupt()
    {
        $this->__load();
        return parent::getInterupt();
    }

    public function setDateInterupt($dateInterupt)
    {
        $this->__load();
        return parent::setDateInterupt($dateInterupt);
    }

    public function getDateInterupt()
    {
        $this->__load();
        return parent::getDateInterupt();
    }

    public function setSommePeriode($sommePeriode)
    {
        $this->__load();
        return parent::setSommePeriode($sommePeriode);
    }

    public function getSommePeriode()
    {
        $this->__load();
        return parent::getSommePeriode();
    }

    public function setSommeTotal($sommeTotal)
    {
        $this->__load();
        return parent::setSommeTotal($sommeTotal);
    }

    public function getSommeTotal()
    {
        $this->__load();
        return parent::getSommeTotal();
    }

    public function setEleve(\EcoleDeMusique\WelcomeBundle\Entity\Eleve $eleve = NULL)
    {
        $this->__load();
        return parent::setEleve($eleve);
    }

    public function getEleve()
    {
        $this->__load();
        return parent::getEleve();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'interupt', 'dateInterupt', 'sommePeriode', 'sommeTotal', 'eleve');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}