<?php

namespace Proxies\__CG__\EcoleDeMusique\WelcomeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PaiementPeriode extends \EcoleDeMusique\WelcomeBundle\Entity\PaiementPeriode implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNumeraire($numeraire)
    {
        $this->__load();
        return parent::setNumeraire($numeraire);
    }

    public function getNumeraire()
    {
        $this->__load();
        return parent::getNumeraire();
    }

    public function setChequeJeune($chequeJeune)
    {
        $this->__load();
        return parent::setChequeJeune($chequeJeune);
    }

    public function getChequeJeune()
    {
        $this->__load();
        return parent::getChequeJeune();
    }

    public function setChequeVacance($chequeVacance)
    {
        $this->__load();
        return parent::setChequeVacance($chequeVacance);
    }

    public function getChequeVacance()
    {
        $this->__load();
        return parent::getChequeVacance();
    }

    public function setCheque($cheque)
    {
        $this->__load();
        return parent::setCheque($cheque);
    }

    public function getCheque()
    {
        $this->__load();
        return parent::getCheque();
    }

    public function setNumPeriod($numPeriod)
    {
        $this->__load();
        return parent::setNumPeriod($numPeriod);
    }

    public function getNumPeriod()
    {
        $this->__load();
        return parent::getNumPeriod();
    }

    public function setPaiement(\EcoleDeMusique\WelcomeBundle\Entity\Paiement $paiement = NULL)
    {
        $this->__load();
        return parent::setPaiement($paiement);
    }

    public function getPaiement()
    {
        $this->__load();
        return parent::getPaiement();
    }

    public function setCb($cb)
    {
        $this->__load();
        return parent::setCb($cb);
    }

    public function getCb()
    {
        $this->__load();
        return parent::getCb();
    }

    public function setPrelev($prelev)
    {
        $this->__load();
        return parent::setPrelev($prelev);
    }

    public function getPrelev()
    {
        $this->__load();
        return parent::getPrelev();
    }

    public function setDateNumeraire($dateNumeraire)
    {
        $this->__load();
        return parent::setDateNumeraire($dateNumeraire);
    }

    public function getDateNumeraire()
    {
        $this->__load();
        return parent::getDateNumeraire();
    }

    public function setDateChequeJeune($dateChequeJeune)
    {
        $this->__load();
        return parent::setDateChequeJeune($dateChequeJeune);
    }

    public function getDateChequeJeune()
    {
        $this->__load();
        return parent::getDateChequeJeune();
    }

    public function setDateChequeVacance($dateChequeVacance)
    {
        $this->__load();
        return parent::setDateChequeVacance($dateChequeVacance);
    }

    public function getDateChequeVacance()
    {
        $this->__load();
        return parent::getDateChequeVacance();
    }

    public function setDateCheque($dateCheque)
    {
        $this->__load();
        return parent::setDateCheque($dateCheque);
    }

    public function getDateCheque()
    {
        $this->__load();
        return parent::getDateCheque();
    }

    public function setDateCb($dateCb)
    {
        $this->__load();
        return parent::setDateCb($dateCb);
    }

    public function getDateCb()
    {
        $this->__load();
        return parent::getDateCb();
    }

    public function setDatePrelev($datePrelev)
    {
        $this->__load();
        return parent::setDatePrelev($datePrelev);
    }

    public function getDatePrelev()
    {
        $this->__load();
        return parent::getDatePrelev();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'numPeriod', 'numeraire', 'chequeJeune', 'chequeVacance', 'cheque', 'cb', 'prelev', 'dateNumeraire', 'dateChequeJeune', 'dateChequeVacance', 'dateCheque', 'dateCb', 'datePrelev', 'paiement');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}