<?php

namespace Proxies\__CG__\EcoleDeMusique\WelcomeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PaiementPeriode extends \EcoleDeMusique\WelcomeBundle\Entity\PaiementPeriode implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'id', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'numPeriod', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'numeraire', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'chequeJeune', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'chequeVacance', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'cheque', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'cb', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'prelev', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'dateNumeraire', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'dateChequeJeune', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'dateChequeVacance', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'dateCheque', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'dateCb', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'datePrelev', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'paiement');
        }

        return array('__isInitialized__', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'id', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'numPeriod', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'numeraire', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'chequeJeune', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'chequeVacance', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'cheque', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'cb', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'prelev', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'dateNumeraire', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'dateChequeJeune', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'dateChequeVacance', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'dateCheque', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'dateCb', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'datePrelev', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\PaiementPeriode' . "\0" . 'paiement');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PaiementPeriode $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumPeriod($numPeriod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumPeriod', array($numPeriod));

        return parent::setNumPeriod($numPeriod);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumPeriod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumPeriod', array());

        return parent::getNumPeriod();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeraire($numeraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeraire', array($numeraire));

        return parent::setNumeraire($numeraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeraire', array());

        return parent::getNumeraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setChequejeune($chequeJeune)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChequejeune', array($chequeJeune));

        return parent::setChequejeune($chequeJeune);
    }

    /**
     * {@inheritDoc}
     */
    public function getChequejeune()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChequejeune', array());

        return parent::getChequejeune();
    }

    /**
     * {@inheritDoc}
     */
    public function setChequevacance($chequeVacance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChequevacance', array($chequeVacance));

        return parent::setChequevacance($chequeVacance);
    }

    /**
     * {@inheritDoc}
     */
    public function getChequevacance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChequevacance', array());

        return parent::getChequevacance();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheque($cheque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheque', array($cheque));

        return parent::setCheque($cheque);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheque', array());

        return parent::getCheque();
    }

    /**
     * {@inheritDoc}
     */
    public function setCb($cb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCb', array($cb));

        return parent::setCb($cb);
    }

    /**
     * {@inheritDoc}
     */
    public function getCb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCb', array());

        return parent::getCb();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrelev($prelev)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrelev', array($prelev));

        return parent::setPrelev($prelev);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrelev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrelev', array());

        return parent::getPrelev();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNumeraire($dateNumeraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNumeraire', array($dateNumeraire));

        return parent::setDateNumeraire($dateNumeraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNumeraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNumeraire', array());

        return parent::getDateNumeraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateChequeJeune($dateChequeJeune)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateChequeJeune', array($dateChequeJeune));

        return parent::setDateChequeJeune($dateChequeJeune);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateChequeJeune()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateChequeJeune', array());

        return parent::getDateChequeJeune();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateChequeVacance($dateChequeVacance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateChequeVacance', array($dateChequeVacance));

        return parent::setDateChequeVacance($dateChequeVacance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateChequeVacance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateChequeVacance', array());

        return parent::getDateChequeVacance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCheque($dateCheque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCheque', array($dateCheque));

        return parent::setDateCheque($dateCheque);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecheque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecheque', array());

        return parent::getDatecheque();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCb($dateCb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCb', array($dateCb));

        return parent::setDateCb($dateCb);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCb', array());

        return parent::getDateCb();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatePrelev($datePrelev)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatePrelev', array($datePrelev));

        return parent::setDatePrelev($datePrelev);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatePrelev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatePrelev', array());

        return parent::getDatePrelev();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaiement(\EcoleDeMusique\WelcomeBundle\Entity\Paiement $paiement = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaiement', array($paiement));

        return parent::setPaiement($paiement);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaiement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaiement', array());

        return parent::getPaiement();
    }

}
