<?php

namespace Proxies\__CG__\EcoleDeMusique\WelcomeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Archive extends \EcoleDeMusique\WelcomeBundle\Entity\Archive implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'id', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'nom', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'prenom', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'dateDeNaissance', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'cycle', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'instru1', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'instru2', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'anneeActivite', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'interuptionCourannee');
        }

        return array('__isInitialized__', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'id', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'nom', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'prenom', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'dateDeNaissance', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'cycle', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'instru1', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'instru2', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'anneeActivite', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Archive' . "\0" . 'interuptionCourannee');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Archive $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeNaissance($dateDeNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeNaissance', array($dateDeNaissance));

        return parent::setDateDeNaissance($dateDeNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeNaissance', array());

        return parent::getDateDeNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setCycle($cycle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCycle', array($cycle));

        return parent::setCycle($cycle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCycle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCycle', array());

        return parent::getCycle();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstru1($instru1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstru1', array($instru1));

        return parent::setInstru1($instru1);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstru1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstru1', array());

        return parent::getInstru1();
    }

    /**
     * {@inheritDoc}
     */
    public function setInstru2($instru2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInstru2', array($instru2));

        return parent::setInstru2($instru2);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstru2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstru2', array());

        return parent::getInstru2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneeActivite($anneeActivite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneeActivite', array($anneeActivite));

        return parent::setAnneeActivite($anneeActivite);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneeActivite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneeActivite', array());

        return parent::getAnneeActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setInteruptionCourannee($interuptionCourannee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInteruptionCourannee', array($interuptionCourannee));

        return parent::setInteruptionCourannee($interuptionCourannee);
    }

    /**
     * {@inheritDoc}
     */
    public function getInteruptionCourannee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInteruptionCourannee', array());

        return parent::getInteruptionCourannee();
    }

}
