<?php

namespace Proxies\__CG__\EcoleDeMusique\WelcomeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Eleve extends \EcoleDeMusique\WelcomeBundle\Entity\Eleve implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'id', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'nom', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'prenom', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'adresse', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'codePostal', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'civilite', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'telEleve', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'telMere', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'telPere', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'dateDeNaissance', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'mail', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'regie', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'famille', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'paiement', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'eleves', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'ville');
        }

        return array('__isInitialized__', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'id', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'nom', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'prenom', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'adresse', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'codePostal', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'civilite', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'telEleve', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'telMere', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'telPere', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'dateDeNaissance', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'mail', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'regie', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'famille', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'paiement', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'eleves', '' . "\0" . 'EcoleDeMusique\\WelcomeBundle\\Entity\\Eleve' . "\0" . 'ville');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Eleve $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($codePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', array($codePostal));

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', array());

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCivilite($civilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCivilite', array($civilite));

        return parent::setCivilite($civilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getCivilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCivilite', array());

        return parent::getCivilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelEleve($telEleve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelEleve', array($telEleve));

        return parent::setTelEleve($telEleve);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelEleve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelEleve', array());

        return parent::getTelEleve();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelMere($telMere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelMere', array($telMere));

        return parent::setTelMere($telMere);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelMere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelMere', array());

        return parent::getTelMere();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelPere($telPere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelPere', array($telPere));

        return parent::setTelPere($telPere);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelPere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelPere', array());

        return parent::getTelPere();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeNaissance($dateDeNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeNaissance', array($dateDeNaissance));

        return parent::setDateDeNaissance($dateDeNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeNaissance', array());

        return parent::getDateDeNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setMail($mail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMail', array($mail));

        return parent::setMail($mail);
    }

    /**
     * {@inheritDoc}
     */
    public function getMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', array());

        return parent::getMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegie(\EcoleDeMusique\WelcomeBundle\Entity\Regie $regie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegie', array($regie));

        return parent::setRegie($regie);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegie', array());

        return parent::getRegie();
    }

    /**
     * {@inheritDoc}
     */
    public function setFamille(\EcoleDeMusique\WelcomeBundle\Entity\Famille $famille = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFamille', array($famille));

        return parent::setFamille($famille);
    }

    /**
     * {@inheritDoc}
     */
    public function getFamille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFamille', array());

        return parent::getFamille();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaiement(\EcoleDeMusique\WelcomeBundle\Entity\Paiement $paiement = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaiement', array($paiement));

        return parent::setPaiement($paiement);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaiement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaiement', array());

        return parent::getPaiement();
    }

    /**
     * {@inheritDoc}
     */
    public function addEleve(\EcoleDeMusique\WelcomeBundle\Entity\CoursEleve $eleve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEleve', array($eleve));

        return parent::addEleve($eleve);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEleve(\EcoleDeMusique\WelcomeBundle\Entity\CoursEleve $eleve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEleve', array($eleve));

        return parent::removeEleve($eleve);
    }

    /**
     * {@inheritDoc}
     */
    public function getEleves()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEleves', array());

        return parent::getEleves();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function addActivite(\EcoleDeMusique\WelcomeBundle\Entity\ActiviteEleve $activites)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActivite', array($activites));

        return parent::addActivite($activites);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActivite(\EcoleDeMusique\WelcomeBundle\Entity\ActiviteEleve $activites)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActivite', array($activites));

        return parent::removeActivite($activites);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivites()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivites', array());

        return parent::getActivites();
    }

    /**
     * {@inheritDoc}
     */
    public function findremisebyeleve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findremisebyeleve', array());

        return parent::findremisebyeleve();
    }

    /**
     * {@inheritDoc}
     */
    public function findSommeAvecRemise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'findSommeAvecRemise', array());

        return parent::findSommeAvecRemise();
    }

}
