EcoleDeMusique\WelcomeBundle\Entity\Cours:
   type: entity
   table: cours
   id:
        id:
            type: integer
            generator: { strategy: AUTO }
   fields:
      dateDeb:
          type: datetime
          notnull: true
      dateFin:
          type: datetime
          notnull: true
   manyToOne:
        prof:
            targetEntity: Prof
            inversedBy: profs
            joinColumn:
                name: prof_id
                referencedColumnName: id   
        salle:
            targetEntity: Salle
            inversedBy: salles
            joinColumn:
                name: salle_id
                referencedColumnName: id   
        activite:
            targetEntity: Activite
            inversedBy: activites
            joinColumn:
                name: activite_id
                referencedColumnName: id   
   oneToMany:
        courss:
          targetEntity: CoursEleve
          mappedBy: cours