EcoleDeMusique\WelcomeBundle\Entity\CoursEleve:
   type: entity
   table: CoursEleve
   id:
        id:
            type: integer
            generator: { strategy: AUTO }
   manyToOne:
        cours:
            targetEntity: Cours
            inversedBy: courss
            joinColumn:
                name: cours_id
                referencedColumnName: id        
        eleve:
            targetEntity: Eleve
            inversedBy: eleves
            joinColumn:
                name: eleve_id
                referencedColumnName: id   