EcoleDeMusique\WelcomeBundle\Entity\Famille:
   type: entity
   table: famille
   id:
        id:
            type: integer
            generator: { strategy: AUTO }
   fields:
        qf:
            type: integer 
            nullable: true
            nullable: true   
   oneToMany:
        eleves:
          targetEntity: Eleve
          mappedBy: famille
   oneToOne:
       responsable:
           targetEntity: Eleve
           