EcoleDeMusique\WelcomeBundle\Entity\Mailing:
   type: entity
   table: mailing
   id:
        id:
            type: integer
            generator: { strategy: AUTO }
   fields:
        titre:
            type: string 
            length: 50
            nullable: false
        message:
            type: string
            length: 500
            nullable: true
        nomActivite:
            type: string
            length: 500
            nullable: true
   ManyToMany:
        eleves:
          targetEntity: ActiviteEleves
          mappedBy: mailings
     