EcoleDeMusique\WelcomeBundle\Entity\Prof:
   type: entity
   table: prof
   id:
        id:
            type: integer
            generator: { strategy: AUTO }
   fields:
      nom:
          type: string
          length: 255
      prenom:
          type: string
          length: 255
   OneToMany:
        profs:
          targetEntity: Cours
          mappedBy: prof