EcoleDeMusique\WelcomeBundle\Entity\Salle:
   type: entity
   table: salle
   id:
        id:
            type: integer
            generator: { strategy: AUTO }
   fields:
        nom:
          type: string
          length: 255
   OneToMany:
        salles:
          targetEntity: Cours
          mappedBy: salle