EcoleDeMusique\WelcomeBundle\Entity\User:
   type: entity
   table: User
   id:
        id:
            type: integer
            generator: { strategy: AUTO }
   fields:
        login:
            type : string
        mdp:
            type: string
        role:
            type: string